/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An action is an object that can be executed in WordPress to perform a particular task according to its capabilities.
 */
export type Action = Action1 & Action2;
export type Action1 = BaseAction;
export type Action2 = NavigateAction | RunAction | CodeAction | MessageAction;
export type NavigateAction = {
  capability?: PerformsAStandardPageNavigationWithinWordPressUsingWindowLocation;
  /**
   * The URL to navigate to.
   */
  url: string;
  [k: string]: unknown;
};
export type PerformsAStandardPageNavigationWithinWordPressUsingWindowLocation = "navigate";
export type RunAction = {
  capability?: RunsAWPCLICommandInTheWordPressInstallation;
  /**
   * The WP CLI command to run.
   */
  command: string;
  /**
   * Arguments for the command.
   */
  args?: string[];
  [k: string]: unknown;
};
export type RunsAWPCLICommandInTheWordPressInstallation = "run";
export type CodeAction = {
  capability?: CodeToBeExecutedInTheWordPressEnvironment;
  /**
   * The absolute file path to the code.
   */
  file: string;
  [k: string]: unknown;
};
export type CodeToBeExecutedInTheWordPressEnvironment = "code";
export type SendsAMessageToTheAgentWPDialogInterfaceForTheUserToRespondTo = "message";

export interface BaseAction {
  /**
   * The capability of the Action defines what it's able to do when executed by the WordPress client.
   */
  capability: string;
  [k: string]: unknown;
}
export interface MessageAction {
  capability?: SendsAMessageToTheAgentWPDialogInterfaceForTheUserToRespondTo;
  /**
   * The text of the message in markdown.
   */
  text: string;
  buttons?: {
    label: string;
    url: string;
    level?: "primary" | "secondary" | "danger" | "success";
    [k: string]: unknown;
  }[];
  graph?: {
    graphType: string;
    title?: string;
    data: {
      label: string;
      value: number;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
